//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ArxivarSAPIntegration.SalesOrderGet {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesOrderGetSOAP", Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGet : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallSalesOrderGetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesOrderGet() {
            this.Url = global::ArxivarSAPIntegration.Properties.Settings.Default.ArxivarSAPIntegration_SalesOrderGet_SalesOrderGet;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallSalesOrderGetCompletedEventHandler CallSalesOrderGetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.culligan.it/SalesOrderGet", RequestElementName="SalesOrderGet", RequestNamespace="http://www.culligan.it/SalesOrderGet/", ResponseElementName="SalesOrderGetResponse", ResponseNamespace="http://www.culligan.it/SalesOrderGet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("A_SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderType[] CallSalesOrderGet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LastRunDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Type) {
            object[] results = this.Invoke("CallSalesOrderGet", new object[] {
                        LastRunDate,
                        Type});
            return ((SalesOrderGetResponseA_SalesOrderType[])(results[0]));
        }
        
        /// <remarks/>
        public void CallSalesOrderGetAsync(string LastRunDate, string Type) {
            this.CallSalesOrderGetAsync(LastRunDate, Type, null);
        }
        
        /// <remarks/>
        public void CallSalesOrderGetAsync(string LastRunDate, string Type, object userState) {
            if ((this.CallSalesOrderGetOperationCompleted == null)) {
                this.CallSalesOrderGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallSalesOrderGetOperationCompleted);
            }
            this.InvokeAsync("CallSalesOrderGet", new object[] {
                        LastRunDate,
                        Type}, this.CallSalesOrderGetOperationCompleted, userState);
        }
        
        private void OnCallSalesOrderGetOperationCompleted(object arg) {
            if ((this.CallSalesOrderGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallSalesOrderGetCompleted(this, new CallSalesOrderGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderType {
        
        private string[] salesOrderField;
        
        private string[] requestedDeliveryDateField;
        
        private string[] overallSDDocumentRejectionStsField;
        
        private string[] distributionChannelField;
        
        private string[] organizationDivisionField;
        
        private string[] overallTotalDeliveryStatusField;
        
        private string[] overallSDProcessStatusField;
        
        private string[] assignmentReferenceField;
        
        private string[] paymentMethodField;
        
        private string[] creationDateField;
        
        private string[] createdByUserField;
        
        private string[] lastChangeDateField;
        
        private string[] lastChangestringField;
        
        private string[] purchaseOrderByCustomerField;
        
        private string[] customerPurchaseOrderTypeField;
        
        private string[] customerPurchaseOrderDateField;
        
        private string[] customerPaymentTermsField;
        
        private string[] incotermsVersionField;
        
        private string[] incotermsLocation2Field;
        
        private string[] incotermsLocation1Field;
        
        private string[] pricingDateField;
        
        private string[] incotermsTransferLocationField;
        
        private string[] incotermsClassificationField;
        
        private System.Nullable<bool>[] completeDeliveryIsDefinedField;
        
        private string[] deliveryBlockReasonField;
        
        private string[] headerBillingBlockReasonField;
        
        private string[] salesDistrictField;
        
        private string[] shippingTypeField;
        
        private string[] salesOrderTypeField;
        
        private string[] sDDocumentReasonField;
        
        private string[] salesOrganizationField;
        
        private string[] salesGroupField;
        
        private string[] salesOrderDateField;
        
        private string[] salesOfficeField;
        
        private string[] shippingConditionField;
        
        private string[] soldToPartyField;
        
        private string[] totalCreditCheckStatusField;
        
        private string[] totalNetAmountField;
        
        private string[] transactionCurrencyField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemType[] to_ItemField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_PartnerA_SalesOrderHeaderPartnerType[] to_PartnerField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_PricingElementA_SalesOrderHeaderPrElementType[] to_PricingElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestedDeliveryDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] RequestedDeliveryDate {
            get {
                return this.requestedDeliveryDateField;
            }
            set {
                this.requestedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OverallSDDocumentRejectionSts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OverallSDDocumentRejectionSts {
            get {
                return this.overallSDDocumentRejectionStsField;
            }
            set {
                this.overallSDDocumentRejectionStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DistributionChannel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DistributionChannel {
            get {
                return this.distributionChannelField;
            }
            set {
                this.distributionChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganizationDivision", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OrganizationDivision {
            get {
                return this.organizationDivisionField;
            }
            set {
                this.organizationDivisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OverallTotalDeliveryStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OverallTotalDeliveryStatus {
            get {
                return this.overallTotalDeliveryStatusField;
            }
            set {
                this.overallTotalDeliveryStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OverallSDProcessStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OverallSDProcessStatus {
            get {
                return this.overallSDProcessStatusField;
            }
            set {
                this.overallSDProcessStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssignmentReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] AssignmentReference {
            get {
                return this.assignmentReferenceField;
            }
            set {
                this.assignmentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PaymentMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreatedByUser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreatedByUser {
            get {
                return this.createdByUserField;
            }
            set {
                this.createdByUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LastChangeDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] LastChangeDate {
            get {
                return this.lastChangeDateField;
            }
            set {
                this.lastChangeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LastChangestring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] LastChangestring {
            get {
                return this.lastChangestringField;
            }
            set {
                this.lastChangestringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrderByCustomer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PurchaseOrderByCustomer {
            get {
                return this.purchaseOrderByCustomerField;
            }
            set {
                this.purchaseOrderByCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerPurchaseOrderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CustomerPurchaseOrderType {
            get {
                return this.customerPurchaseOrderTypeField;
            }
            set {
                this.customerPurchaseOrderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerPurchaseOrderDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CustomerPurchaseOrderDate {
            get {
                return this.customerPurchaseOrderDateField;
            }
            set {
                this.customerPurchaseOrderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerPaymentTerms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CustomerPaymentTerms {
            get {
                return this.customerPaymentTermsField;
            }
            set {
                this.customerPaymentTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsVersion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsVersion {
            get {
                return this.incotermsVersionField;
            }
            set {
                this.incotermsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsLocation2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsLocation2 {
            get {
                return this.incotermsLocation2Field;
            }
            set {
                this.incotermsLocation2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsLocation1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsLocation1 {
            get {
                return this.incotermsLocation1Field;
            }
            set {
                this.incotermsLocation1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingDate {
            get {
                return this.pricingDateField;
            }
            set {
                this.pricingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsTransferLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsTransferLocation {
            get {
                return this.incotermsTransferLocationField;
            }
            set {
                this.incotermsTransferLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsClassification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsClassification {
            get {
                return this.incotermsClassificationField;
            }
            set {
                this.incotermsClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompleteDeliveryIsDefined", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] CompleteDeliveryIsDefined {
            get {
                return this.completeDeliveryIsDefinedField;
            }
            set {
                this.completeDeliveryIsDefinedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryBlockReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DeliveryBlockReason {
            get {
                return this.deliveryBlockReasonField;
            }
            set {
                this.deliveryBlockReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HeaderBillingBlockReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] HeaderBillingBlockReason {
            get {
                return this.headerBillingBlockReasonField;
            }
            set {
                this.headerBillingBlockReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesDistrict", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesDistrict {
            get {
                return this.salesDistrictField;
            }
            set {
                this.salesDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ShippingType {
            get {
                return this.shippingTypeField;
            }
            set {
                this.shippingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOrderType {
            get {
                return this.salesOrderTypeField;
            }
            set {
                this.salesOrderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SDDocumentReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SDDocumentReason {
            get {
                return this.sDDocumentReasonField;
            }
            set {
                this.sDDocumentReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrganization", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOrganization {
            get {
                return this.salesOrganizationField;
            }
            set {
                this.salesOrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesGroup {
            get {
                return this.salesGroupField;
            }
            set {
                this.salesGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOrderDate {
            get {
                return this.salesOrderDateField;
            }
            set {
                this.salesOrderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOffice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOffice {
            get {
                return this.salesOfficeField;
            }
            set {
                this.salesOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ShippingCondition {
            get {
                return this.shippingConditionField;
            }
            set {
                this.shippingConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoldToParty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SoldToParty {
            get {
                return this.soldToPartyField;
            }
            set {
                this.soldToPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalCreditCheckStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TotalCreditCheckStatus {
            get {
                return this.totalCreditCheckStatusField;
            }
            set {
                this.totalCreditCheckStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalNetAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TotalNetAmount {
            get {
                return this.totalNetAmountField;
            }
            set {
                this.totalNetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TransactionCurrency {
            get {
                return this.transactionCurrencyField;
            }
            set {
                this.transactionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderItemType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemType[] to_Item {
            get {
                return this.to_ItemField;
            }
            set {
                this.to_ItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderHeaderPartnerType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_PartnerA_SalesOrderHeaderPartnerType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_PartnerA_SalesOrderHeaderPartnerType[] to_Partner {
            get {
                return this.to_PartnerField;
            }
            set {
                this.to_PartnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderHeaderPrElementType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_PricingElementA_SalesOrderHeaderPrElementType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_PricingElementA_SalesOrderHeaderPrElementType[] to_PricingElement {
            get {
                return this.to_PricingElementField;
            }
            set {
                this.to_PricingElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemType {
        
        private string[] salesOrderField;
        
        private string[] salesOrderItemField;
        
        private string[] higherLevelItemField;
        
        private string[] salesOrderItemCategoryField;
        
        private string[] salesOrderItemTextField;
        
        private string[] purchaseOrderByCustomerField;
        
        private string[] materialField;
        
        private string[] materialByCustomerField;
        
        private string[] pricingDateField;
        
        private string[] requestedQuantityField;
        
        private string[] requestedQuantityUnitField;
        
        private string[] itemGrossWeightField;
        
        private string[] itemNetWeightField;
        
        private string[] itemWeightUnitField;
        
        private string[] itemVolumeField;
        
        private string[] itemVolumeUnitField;
        
        private string[] orderRelatedBillingStatusField;
        
        private string[] netAmountField;
        
        private string[] materialGroupField;
        
        private string[] batchField;
        
        private string[] productionPlantField;
        
        private string[] storageLocationField;
        
        private string[] deliveryGroupField;
        
        private string[] shippingPointField;
        
        private string[] shippingTypeField;
        
        private string[] deliveryPriorityField;
        
        private string[] incotermsClassificationField;
        
        private string[] incotermsTransferLocationField;
        
        private string[] incotermsLocation1Field;
        
        private string[] incotermsLocation2Field;
        
        private string[] customerPaymentTermsField;
        
        private string[] salesDocumentRjcnReasonField;
        
        private string[] itemBillingBlockReasonField;
        
        private string[] sDProcessStatusField;
        
        private string[] deliveryStatusField;
        
        private string[] transactionCurrencyField;
        
        private string[] yY1_Equipment_SDIField;
        
        private string[] yY1_TaskList_SDIField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PartnerA_SalesOrderItemPartnerType[] to_PartnerField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PricingElementA_SalesOrderItemPrElementType[] to_PricingElementField;
        
        private SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_ScheduleLineA_SalesOrderScheduleLineType[] to_ScheduleLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrderItem {
            get {
                return this.salesOrderItemField;
            }
            set {
                this.salesOrderItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HigherLevelItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] HigherLevelItem {
            get {
                return this.higherLevelItemField;
            }
            set {
                this.higherLevelItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItemCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOrderItemCategory {
            get {
                return this.salesOrderItemCategoryField;
            }
            set {
                this.salesOrderItemCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItemText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesOrderItemText {
            get {
                return this.salesOrderItemTextField;
            }
            set {
                this.salesOrderItemTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrderByCustomer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PurchaseOrderByCustomer {
            get {
                return this.purchaseOrderByCustomerField;
            }
            set {
                this.purchaseOrderByCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Material", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialByCustomer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] MaterialByCustomer {
            get {
                return this.materialByCustomerField;
            }
            set {
                this.materialByCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingDate {
            get {
                return this.pricingDateField;
            }
            set {
                this.pricingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestedQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] RequestedQuantity {
            get {
                return this.requestedQuantityField;
            }
            set {
                this.requestedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestedQuantityUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] RequestedQuantityUnit {
            get {
                return this.requestedQuantityUnitField;
            }
            set {
                this.requestedQuantityUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGrossWeight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemGrossWeight {
            get {
                return this.itemGrossWeightField;
            }
            set {
                this.itemGrossWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemNetWeight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemNetWeight {
            get {
                return this.itemNetWeightField;
            }
            set {
                this.itemNetWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemWeightUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemWeightUnit {
            get {
                return this.itemWeightUnitField;
            }
            set {
                this.itemWeightUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemVolume", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemVolume {
            get {
                return this.itemVolumeField;
            }
            set {
                this.itemVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemVolumeUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemVolumeUnit {
            get {
                return this.itemVolumeUnitField;
            }
            set {
                this.itemVolumeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderRelatedBillingStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OrderRelatedBillingStatus {
            get {
                return this.orderRelatedBillingStatusField;
            }
            set {
                this.orderRelatedBillingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] NetAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] MaterialGroup {
            get {
                return this.materialGroupField;
            }
            set {
                this.materialGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Batch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductionPlant", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ProductionPlant {
            get {
                return this.productionPlantField;
            }
            set {
                this.productionPlantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StorageLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] StorageLocation {
            get {
                return this.storageLocationField;
            }
            set {
                this.storageLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DeliveryGroup {
            get {
                return this.deliveryGroupField;
            }
            set {
                this.deliveryGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ShippingPoint {
            get {
                return this.shippingPointField;
            }
            set {
                this.shippingPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ShippingType {
            get {
                return this.shippingTypeField;
            }
            set {
                this.shippingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryPriority", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DeliveryPriority {
            get {
                return this.deliveryPriorityField;
            }
            set {
                this.deliveryPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsClassification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsClassification {
            get {
                return this.incotermsClassificationField;
            }
            set {
                this.incotermsClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsTransferLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsTransferLocation {
            get {
                return this.incotermsTransferLocationField;
            }
            set {
                this.incotermsTransferLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsLocation1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsLocation1 {
            get {
                return this.incotermsLocation1Field;
            }
            set {
                this.incotermsLocation1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncotermsLocation2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IncotermsLocation2 {
            get {
                return this.incotermsLocation2Field;
            }
            set {
                this.incotermsLocation2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerPaymentTerms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CustomerPaymentTerms {
            get {
                return this.customerPaymentTermsField;
            }
            set {
                this.customerPaymentTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesDocumentRjcnReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SalesDocumentRjcnReason {
            get {
                return this.salesDocumentRjcnReasonField;
            }
            set {
                this.salesDocumentRjcnReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemBillingBlockReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ItemBillingBlockReason {
            get {
                return this.itemBillingBlockReasonField;
            }
            set {
                this.itemBillingBlockReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SDProcessStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] SDProcessStatus {
            get {
                return this.sDProcessStatusField;
            }
            set {
                this.sDProcessStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DeliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TransactionCurrency {
            get {
                return this.transactionCurrencyField;
            }
            set {
                this.transactionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YY1_Equipment_SDI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] YY1_Equipment_SDI {
            get {
                return this.yY1_Equipment_SDIField;
            }
            set {
                this.yY1_Equipment_SDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YY1_TaskList_SDI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] YY1_TaskList_SDI {
            get {
                return this.yY1_TaskList_SDIField;
            }
            set {
                this.yY1_TaskList_SDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderItemPartnerType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PartnerA_SalesOrderItemPartnerType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PartnerA_SalesOrderItemPartnerType[] to_Partner {
            get {
                return this.to_PartnerField;
            }
            set {
                this.to_PartnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderItemPrElementType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PricingElementA_SalesOrderItemPrElementType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PricingElementA_SalesOrderItemPrElementType[] to_PricingElement {
            get {
                return this.to_PricingElementField;
            }
            set {
                this.to_PricingElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_SalesOrderScheduleLineType", typeof(SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_ScheduleLineA_SalesOrderScheduleLineType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_ScheduleLineA_SalesOrderScheduleLineType[] to_ScheduleLine {
            get {
                return this.to_ScheduleLineField;
            }
            set {
                this.to_ScheduleLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PartnerA_SalesOrderItemPartnerType {
        
        private string[] partnerFunctionField;
        
        private string[] salesOrderField;
        
        private string[] salesOrderItemField;
        
        private string[] contactPersonField;
        
        private string[] customerField;
        
        private string[] personnelField;
        
        private string[] supplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PartnerFunction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PartnerFunction {
            get {
                return this.partnerFunctionField;
            }
            set {
                this.partnerFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrderItem {
            get {
                return this.salesOrderItemField;
            }
            set {
                this.salesOrderItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactPerson", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Personnel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Personnel {
            get {
                return this.personnelField;
            }
            set {
                this.personnelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_PricingElementA_SalesOrderItemPrElementType {
        
        private string[] pricingProcedureCounterField;
        
        private string[] pricingProcedureStepField;
        
        private string[] salesOrderField;
        
        private string[] salesOrderItemField;
        
        private string[] conditionTypeField;
        
        private string[] pricingstringField;
        
        private string[] conditionCalculationTypeField;
        
        private string[] conditionBaseValueField;
        
        private string[] conditionRateValueField;
        
        private string[] conditionCurrencyField;
        
        private string[] conditionQuantityField;
        
        private string[] conditionQuantityUnitField;
        
        private string[] conditionCategoryField;
        
        private System.Nullable<bool>[] conditionIsForStatisticsField;
        
        private string[] pricingScaleTypeField;
        
        private System.Nullable<bool>[] isRelevantForAccrualField;
        
        private string[] cndnIsRelevantForInvoiceListField;
        
        private string[] conditionOriginField;
        
        private string[] isGroupConditionField;
        
        private string[] conditionRecordField;
        
        private string[] conditionSequentialNumberField;
        
        private string[] taxCodeField;
        
        private System.Nullable<bool>[] conditionIsForConfigurationField;
        
        private string[] cndnRoundingOffDiffAmountField;
        
        private string[] conditionAmountField;
        
        private System.Nullable<bool>[] conditionIsManuallyChangedField;
        
        private string[] conditionControlField;
        
        private string[] conditionInactiveReasonField;
        
        private string[] conditionClassField;
        
        private string[] prcgProcedureCounterForHeaderField;
        
        private System.Nullable<double>[] factorForConditionBasisValueField;
        
        private string[] structureConditionField;
        
        private System.Nullable<double>[] periodFactorForCndnBasisValueField;
        
        private string[] pricingScaleBasisField;
        
        private string[] conditionScaleBasisValueField;
        
        private string[] conditionScaleBasisUnitField;
        
        private string[] conditionScaleBasisCurrencyField;
        
        private System.Nullable<bool>[] cndnIsRelevantForIntcoBillingField;
        
        private string[] transactionCurrencyField;
        
        private string[] variantConditionField;
        
        private string[] withholdingTaxCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingProcedureCounter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PricingProcedureCounter {
            get {
                return this.pricingProcedureCounterField;
            }
            set {
                this.pricingProcedureCounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingProcedureStep", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PricingProcedureStep {
            get {
                return this.pricingProcedureStepField;
            }
            set {
                this.pricingProcedureStepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrderItem {
            get {
                return this.salesOrderItemField;
            }
            set {
                this.salesOrderItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pricingstring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Pricingstring {
            get {
                return this.pricingstringField;
            }
            set {
                this.pricingstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCalculationType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCalculationType {
            get {
                return this.conditionCalculationTypeField;
            }
            set {
                this.conditionCalculationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionBaseValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionBaseValue {
            get {
                return this.conditionBaseValueField;
            }
            set {
                this.conditionBaseValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionRateValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionRateValue {
            get {
                return this.conditionRateValueField;
            }
            set {
                this.conditionRateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCurrency {
            get {
                return this.conditionCurrencyField;
            }
            set {
                this.conditionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionQuantity {
            get {
                return this.conditionQuantityField;
            }
            set {
                this.conditionQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionQuantityUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionQuantityUnit {
            get {
                return this.conditionQuantityUnitField;
            }
            set {
                this.conditionQuantityUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCategory {
            get {
                return this.conditionCategoryField;
            }
            set {
                this.conditionCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsForStatistics", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsForStatistics {
            get {
                return this.conditionIsForStatisticsField;
            }
            set {
                this.conditionIsForStatisticsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingScaleType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingScaleType {
            get {
                return this.pricingScaleTypeField;
            }
            set {
                this.pricingScaleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IsRelevantForAccrual", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] IsRelevantForAccrual {
            get {
                return this.isRelevantForAccrualField;
            }
            set {
                this.isRelevantForAccrualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CndnIsRelevantForInvoiceList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CndnIsRelevantForInvoiceList {
            get {
                return this.cndnIsRelevantForInvoiceListField;
            }
            set {
                this.cndnIsRelevantForInvoiceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionOrigin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionOrigin {
            get {
                return this.conditionOriginField;
            }
            set {
                this.conditionOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IsGroupCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IsGroupCondition {
            get {
                return this.isGroupConditionField;
            }
            set {
                this.isGroupConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionRecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionRecord {
            get {
                return this.conditionRecordField;
            }
            set {
                this.conditionRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionSequentialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionSequentialNumber {
            get {
                return this.conditionSequentialNumberField;
            }
            set {
                this.conditionSequentialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsForConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsForConfiguration {
            get {
                return this.conditionIsForConfigurationField;
            }
            set {
                this.conditionIsForConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CndnRoundingOffDiffAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CndnRoundingOffDiffAmount {
            get {
                return this.cndnRoundingOffDiffAmountField;
            }
            set {
                this.cndnRoundingOffDiffAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionAmount {
            get {
                return this.conditionAmountField;
            }
            set {
                this.conditionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsManuallyChanged", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsManuallyChanged {
            get {
                return this.conditionIsManuallyChangedField;
            }
            set {
                this.conditionIsManuallyChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionControl", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionControl {
            get {
                return this.conditionControlField;
            }
            set {
                this.conditionControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionInactiveReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionInactiveReason {
            get {
                return this.conditionInactiveReasonField;
            }
            set {
                this.conditionInactiveReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionClass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionClass {
            get {
                return this.conditionClassField;
            }
            set {
                this.conditionClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrcgProcedureCounterForHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PrcgProcedureCounterForHeader {
            get {
                return this.prcgProcedureCounterForHeaderField;
            }
            set {
                this.prcgProcedureCounterForHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactorForConditionBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double>[] FactorForConditionBasisValue {
            get {
                return this.factorForConditionBasisValueField;
            }
            set {
                this.factorForConditionBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StructureCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] StructureCondition {
            get {
                return this.structureConditionField;
            }
            set {
                this.structureConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodFactorForCndnBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double>[] PeriodFactorForCndnBasisValue {
            get {
                return this.periodFactorForCndnBasisValueField;
            }
            set {
                this.periodFactorForCndnBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingScaleBasis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingScaleBasis {
            get {
                return this.pricingScaleBasisField;
            }
            set {
                this.pricingScaleBasisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisValue {
            get {
                return this.conditionScaleBasisValueField;
            }
            set {
                this.conditionScaleBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisUnit {
            get {
                return this.conditionScaleBasisUnitField;
            }
            set {
                this.conditionScaleBasisUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisCurrency {
            get {
                return this.conditionScaleBasisCurrencyField;
            }
            set {
                this.conditionScaleBasisCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CndnIsRelevantForIntcoBilling", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] CndnIsRelevantForIntcoBilling {
            get {
                return this.cndnIsRelevantForIntcoBillingField;
            }
            set {
                this.cndnIsRelevantForIntcoBillingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TransactionCurrency {
            get {
                return this.transactionCurrencyField;
            }
            set {
                this.transactionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VariantCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] VariantCondition {
            get {
                return this.variantConditionField;
            }
            set {
                this.variantConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WithholdingTaxCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] WithholdingTaxCode {
            get {
                return this.withholdingTaxCodeField;
            }
            set {
                this.withholdingTaxCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_ItemA_SalesOrderItemTypeTo_ScheduleLineA_SalesOrderScheduleLineType {
        
        private string[] salesOrderField;
        
        private string[] salesOrderItemField;
        
        private string[] scheduleLineField;
        
        private string[] confdOrderQtyByMatlAvailCheckField;
        
        private string[] delivBlockReasonForSchedLineField;
        
        private string[] deliveredQtyInOrderQtyUnitField;
        
        private string[] openConfdDelivQtyInOrdQtyUnitField;
        
        private string[] orderQuantityUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrderItem {
            get {
                return this.salesOrderItemField;
            }
            set {
                this.salesOrderItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ScheduleLine {
            get {
                return this.scheduleLineField;
            }
            set {
                this.scheduleLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConfdOrderQtyByMatlAvailCheck", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConfdOrderQtyByMatlAvailCheck {
            get {
                return this.confdOrderQtyByMatlAvailCheckField;
            }
            set {
                this.confdOrderQtyByMatlAvailCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DelivBlockReasonForSchedLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DelivBlockReasonForSchedLine {
            get {
                return this.delivBlockReasonForSchedLineField;
            }
            set {
                this.delivBlockReasonForSchedLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveredQtyInOrderQtyUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DeliveredQtyInOrderQtyUnit {
            get {
                return this.deliveredQtyInOrderQtyUnitField;
            }
            set {
                this.deliveredQtyInOrderQtyUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpenConfdDelivQtyInOrdQtyUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OpenConfdDelivQtyInOrdQtyUnit {
            get {
                return this.openConfdDelivQtyInOrdQtyUnitField;
            }
            set {
                this.openConfdDelivQtyInOrdQtyUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderQuantityUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] OrderQuantityUnit {
            get {
                return this.orderQuantityUnitField;
            }
            set {
                this.orderQuantityUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_PartnerA_SalesOrderHeaderPartnerType {
        
        private string[] partnerFunctionField;
        
        private string[] salesOrderField;
        
        private string[] contactPersonField;
        
        private string[] customerField;
        
        private string[] personnelField;
        
        private string[] supplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PartnerFunction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PartnerFunction {
            get {
                return this.partnerFunctionField;
            }
            set {
                this.partnerFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactPerson", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Personnel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Personnel {
            get {
                return this.personnelField;
            }
            set {
                this.personnelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SalesOrderGet/")]
    public partial class SalesOrderGetResponseA_SalesOrderTypeTo_PricingElementA_SalesOrderHeaderPrElementType {
        
        private string[] pricingProcedureCounterField;
        
        private string[] pricingProcedureStepField;
        
        private string[] salesOrderField;
        
        private string[] conditionTypeField;
        
        private string[] pricingstringField;
        
        private string[] conditionCalculationTypeField;
        
        private string[] conditionBaseValueField;
        
        private string[] conditionRateValueField;
        
        private string[] conditionCurrencyField;
        
        private string[] conditionQuantityField;
        
        private string[] conditionQuantityUnitField;
        
        private string[] conditionCategoryField;
        
        private System.Nullable<bool>[] conditionIsForStatisticsField;
        
        private string[] pricingScaleTypeField;
        
        private string[] conditionOriginField;
        
        private string[] isGroupConditionField;
        
        private string[] conditionRecordField;
        
        private string[] conditionSequentialNumberField;
        
        private string[] taxCodeField;
        
        private string[] withholdingTaxCodeField;
        
        private string[] cndnRoundingOffDiffAmountField;
        
        private string[] conditionAmountField;
        
        private string[] transactionCurrencyField;
        
        private string[] conditionControlField;
        
        private string[] conditionInactiveReasonField;
        
        private string[] conditionClassField;
        
        private string[] prcgProcedureCounterForHeaderField;
        
        private System.Nullable<double>[] factorForConditionBasisValueField;
        
        private string[] structureConditionField;
        
        private System.Nullable<double>[] periodFactorForCndnBasisValueField;
        
        private string[] pricingScaleBasisField;
        
        private string[] conditionScaleBasisValueField;
        
        private string[] conditionScaleBasisUnitField;
        
        private string[] conditionScaleBasisCurrencyField;
        
        private System.Nullable<bool>[] cndnIsRelevantForIntcoBillingField;
        
        private System.Nullable<bool>[] conditionIsManuallyChangedField;
        
        private System.Nullable<bool>[] conditionIsForConfigurationField;
        
        private string[] variantConditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingProcedureCounter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PricingProcedureCounter {
            get {
                return this.pricingProcedureCounterField;
            }
            set {
                this.pricingProcedureCounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingProcedureStep", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PricingProcedureStep {
            get {
                return this.pricingProcedureStepField;
            }
            set {
                this.pricingProcedureStepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesOrder {
            get {
                return this.salesOrderField;
            }
            set {
                this.salesOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pricingstring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Pricingstring {
            get {
                return this.pricingstringField;
            }
            set {
                this.pricingstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCalculationType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCalculationType {
            get {
                return this.conditionCalculationTypeField;
            }
            set {
                this.conditionCalculationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionBaseValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionBaseValue {
            get {
                return this.conditionBaseValueField;
            }
            set {
                this.conditionBaseValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionRateValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionRateValue {
            get {
                return this.conditionRateValueField;
            }
            set {
                this.conditionRateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCurrency {
            get {
                return this.conditionCurrencyField;
            }
            set {
                this.conditionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionQuantity {
            get {
                return this.conditionQuantityField;
            }
            set {
                this.conditionQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionQuantityUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionQuantityUnit {
            get {
                return this.conditionQuantityUnitField;
            }
            set {
                this.conditionQuantityUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionCategory {
            get {
                return this.conditionCategoryField;
            }
            set {
                this.conditionCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsForStatistics", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsForStatistics {
            get {
                return this.conditionIsForStatisticsField;
            }
            set {
                this.conditionIsForStatisticsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingScaleType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingScaleType {
            get {
                return this.pricingScaleTypeField;
            }
            set {
                this.pricingScaleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionOrigin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionOrigin {
            get {
                return this.conditionOriginField;
            }
            set {
                this.conditionOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IsGroupCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] IsGroupCondition {
            get {
                return this.isGroupConditionField;
            }
            set {
                this.isGroupConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionRecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionRecord {
            get {
                return this.conditionRecordField;
            }
            set {
                this.conditionRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionSequentialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionSequentialNumber {
            get {
                return this.conditionSequentialNumberField;
            }
            set {
                this.conditionSequentialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WithholdingTaxCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] WithholdingTaxCode {
            get {
                return this.withholdingTaxCodeField;
            }
            set {
                this.withholdingTaxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CndnRoundingOffDiffAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CndnRoundingOffDiffAmount {
            get {
                return this.cndnRoundingOffDiffAmountField;
            }
            set {
                this.cndnRoundingOffDiffAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionAmount {
            get {
                return this.conditionAmountField;
            }
            set {
                this.conditionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] TransactionCurrency {
            get {
                return this.transactionCurrencyField;
            }
            set {
                this.transactionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionControl", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionControl {
            get {
                return this.conditionControlField;
            }
            set {
                this.conditionControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionInactiveReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionInactiveReason {
            get {
                return this.conditionInactiveReasonField;
            }
            set {
                this.conditionInactiveReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionClass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionClass {
            get {
                return this.conditionClassField;
            }
            set {
                this.conditionClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrcgProcedureCounterForHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PrcgProcedureCounterForHeader {
            get {
                return this.prcgProcedureCounterForHeaderField;
            }
            set {
                this.prcgProcedureCounterForHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FactorForConditionBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double>[] FactorForConditionBasisValue {
            get {
                return this.factorForConditionBasisValueField;
            }
            set {
                this.factorForConditionBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StructureCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] StructureCondition {
            get {
                return this.structureConditionField;
            }
            set {
                this.structureConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodFactorForCndnBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double>[] PeriodFactorForCndnBasisValue {
            get {
                return this.periodFactorForCndnBasisValueField;
            }
            set {
                this.periodFactorForCndnBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PricingScaleBasis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PricingScaleBasis {
            get {
                return this.pricingScaleBasisField;
            }
            set {
                this.pricingScaleBasisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisValue {
            get {
                return this.conditionScaleBasisValueField;
            }
            set {
                this.conditionScaleBasisValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisUnit {
            get {
                return this.conditionScaleBasisUnitField;
            }
            set {
                this.conditionScaleBasisUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionScaleBasisCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ConditionScaleBasisCurrency {
            get {
                return this.conditionScaleBasisCurrencyField;
            }
            set {
                this.conditionScaleBasisCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CndnIsRelevantForIntcoBilling", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] CndnIsRelevantForIntcoBilling {
            get {
                return this.cndnIsRelevantForIntcoBillingField;
            }
            set {
                this.cndnIsRelevantForIntcoBillingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsManuallyChanged", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsManuallyChanged {
            get {
                return this.conditionIsManuallyChangedField;
            }
            set {
                this.conditionIsManuallyChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConditionIsForConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] ConditionIsForConfiguration {
            get {
                return this.conditionIsForConfigurationField;
            }
            set {
                this.conditionIsForConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VariantCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] VariantCondition {
            get {
                return this.variantConditionField;
            }
            set {
                this.variantConditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CallSalesOrderGetCompletedEventHandler(object sender, CallSalesOrderGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallSalesOrderGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallSalesOrderGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderGetResponseA_SalesOrderType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderGetResponseA_SalesOrderType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591