//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ArxivarSapIntegration
{
    #region Contesti
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    public partial class SAP_BIEntities : ObjectContext
    {
        #region Costruttori
    
        /// <summary>
        /// Inizializza un nuovo oggetto SAP_BIEntities utilizzando la stringa di connessione trovata nella sezione 'SAP_BIEntities' del file di configurazione dell'applicazione.
        /// </summary>
        public SAP_BIEntities() : base("name=SAP_BIEntities", "SAP_BIEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto SAP_BIEntities.
        /// </summary>
        public SAP_BIEntities(string connectionString) : base(connectionString, "SAP_BIEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto SAP_BIEntities.
        /// </summary>
        public SAP_BIEntities(EntityConnection connection) : base(connection, "SAP_BIEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Metodi parziali
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Proprietà ObjectSet
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<SAP_Invoice> SAP_Invoice
        {
            get
            {
                if ((_SAP_Invoice == null))
                {
                    _SAP_Invoice = base.CreateObjectSet<SAP_Invoice>("SAP_Invoice");
                }
                return _SAP_Invoice;
            }
        }
        private ObjectSet<SAP_Invoice> _SAP_Invoice;

        #endregion

        #region Metodi AddTo
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet SAP_Invoice. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToSAP_Invoice(SAP_Invoice sAP_Invoice)
        {
            base.AddObject("SAP_Invoice", sAP_Invoice);
        }

        #endregion

    }

    #endregion

    #region Entità
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAP_BIModel", Name="SAP_Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SAP_Invoice : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Crea un nuovo oggetto SAP_Invoice.
        /// </summary>
        /// <param name="id">Valore iniziale della proprietà id.</param>
        /// <param name="billingDocument">Valore iniziale della proprietà BillingDocument.</param>
        public static SAP_Invoice CreateSAP_Invoice(global::System.Int32 id, global::System.String billingDocument)
        {
            SAP_Invoice sAP_Invoice = new SAP_Invoice();
            sAP_Invoice.id = id;
            sAP_Invoice.BillingDocument = billingDocument;
            return sAP_Invoice;
        }

        #endregion

        #region Proprietà semplici
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BillingDocument
        {
            get
            {
                return _BillingDocument;
            }
            set
            {
                if (_BillingDocument != value)
                {
                    OnBillingDocumentChanging(value);
                    ReportPropertyChanging("BillingDocument");
                    _BillingDocument = StructuralObject.SetValidValue(value, false, "BillingDocument");
                    ReportPropertyChanged("BillingDocument");
                    OnBillingDocumentChanged();
                }
            }
        }
        private global::System.String _BillingDocument;
        partial void OnBillingDocumentChanging(global::System.String value);
        partial void OnBillingDocumentChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncotermsLocation2
        {
            get
            {
                return _IncotermsLocation2;
            }
            set
            {
                OnIncotermsLocation2Changing(value);
                ReportPropertyChanging("IncotermsLocation2");
                _IncotermsLocation2 = StructuralObject.SetValidValue(value, true, "IncotermsLocation2");
                ReportPropertyChanged("IncotermsLocation2");
                OnIncotermsLocation2Changed();
            }
        }
        private global::System.String _IncotermsLocation2;
        partial void OnIncotermsLocation2Changing(global::System.String value);
        partial void OnIncotermsLocation2Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingDocumentCategory
        {
            get
            {
                return _BillingDocumentCategory;
            }
            set
            {
                OnBillingDocumentCategoryChanging(value);
                ReportPropertyChanging("BillingDocumentCategory");
                _BillingDocumentCategory = StructuralObject.SetValidValue(value, true, "BillingDocumentCategory");
                ReportPropertyChanged("BillingDocumentCategory");
                OnBillingDocumentCategoryChanged();
            }
        }
        private global::System.String _BillingDocumentCategory;
        partial void OnBillingDocumentCategoryChanging(global::System.String value);
        partial void OnBillingDocumentCategoryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingDocumentType
        {
            get
            {
                return _BillingDocumentType;
            }
            set
            {
                OnBillingDocumentTypeChanging(value);
                ReportPropertyChanging("BillingDocumentType");
                _BillingDocumentType = StructuralObject.SetValidValue(value, true, "BillingDocumentType");
                ReportPropertyChanged("BillingDocumentType");
                OnBillingDocumentTypeChanged();
            }
        }
        private global::System.String _BillingDocumentType;
        partial void OnBillingDocumentTypeChanging(global::System.String value);
        partial void OnBillingDocumentTypeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value, "CreationDate");
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationTime
        {
            get
            {
                return _CreationTime;
            }
            set
            {
                OnCreationTimeChanging(value);
                ReportPropertyChanging("CreationTime");
                _CreationTime = StructuralObject.SetValidValue(value, "CreationTime");
                ReportPropertyChanged("CreationTime");
                OnCreationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationTime;
        partial void OnCreationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationTimeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillingDocumentListDate
        {
            get
            {
                return _BillingDocumentListDate;
            }
            set
            {
                OnBillingDocumentListDateChanging(value);
                ReportPropertyChanging("BillingDocumentListDate");
                _BillingDocumentListDate = StructuralObject.SetValidValue(value, "BillingDocumentListDate");
                ReportPropertyChanged("BillingDocumentListDate");
                OnBillingDocumentListDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillingDocumentListDate;
        partial void OnBillingDocumentListDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillingDocumentListDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingDocumentListType
        {
            get
            {
                return _BillingDocumentListType;
            }
            set
            {
                OnBillingDocumentListTypeChanging(value);
                ReportPropertyChanging("BillingDocumentListType");
                _BillingDocumentListType = StructuralObject.SetValidValue(value, true, "BillingDocumentListType");
                ReportPropertyChanged("BillingDocumentListType");
                OnBillingDocumentListTypeChanged();
            }
        }
        private global::System.String _BillingDocumentListType;
        partial void OnBillingDocumentListTypeChanging(global::System.String value);
        partial void OnBillingDocumentListTypeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingIssueType
        {
            get
            {
                return _BillingIssueType;
            }
            set
            {
                OnBillingIssueTypeChanging(value);
                ReportPropertyChanging("BillingIssueType");
                _BillingIssueType = StructuralObject.SetValidValue(value, true, "BillingIssueType");
                ReportPropertyChanged("BillingIssueType");
                OnBillingIssueTypeChanged();
            }
        }
        private global::System.String _BillingIssueType;
        partial void OnBillingIssueTypeChanging(global::System.String value);
        partial void OnBillingIssueTypeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountingTransferStatus
        {
            get
            {
                return _AccountingTransferStatus;
            }
            set
            {
                OnAccountingTransferStatusChanging(value);
                ReportPropertyChanging("AccountingTransferStatus");
                _AccountingTransferStatus = StructuralObject.SetValidValue(value, true, "AccountingTransferStatus");
                ReportPropertyChanged("AccountingTransferStatus");
                OnAccountingTransferStatusChanged();
            }
        }
        private global::System.String _AccountingTransferStatus;
        partial void OnAccountingTransferStatusChanging(global::System.String value);
        partial void OnAccountingTransferStatusChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DistributionChannel
        {
            get
            {
                return _DistributionChannel;
            }
            set
            {
                OnDistributionChannelChanging(value);
                ReportPropertyChanging("DistributionChannel");
                _DistributionChannel = StructuralObject.SetValidValue(value, true, "DistributionChannel");
                ReportPropertyChanged("DistributionChannel");
                OnDistributionChannelChanged();
            }
        }
        private global::System.String _DistributionChannel;
        partial void OnDistributionChannelChanging(global::System.String value);
        partial void OnDistributionChannelChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true, "Division");
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillingDocumentDate
        {
            get
            {
                return _BillingDocumentDate;
            }
            set
            {
                OnBillingDocumentDateChanging(value);
                ReportPropertyChanging("BillingDocumentDate");
                _BillingDocumentDate = StructuralObject.SetValidValue(value, "BillingDocumentDate");
                ReportPropertyChanged("BillingDocumentDate");
                OnBillingDocumentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillingDocumentDate;
        partial void OnBillingDocumentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillingDocumentDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BillingDocumentIsCancelled
        {
            get
            {
                return _BillingDocumentIsCancelled;
            }
            set
            {
                OnBillingDocumentIsCancelledChanging(value);
                ReportPropertyChanging("BillingDocumentIsCancelled");
                _BillingDocumentIsCancelled = StructuralObject.SetValidValue(value, "BillingDocumentIsCancelled");
                ReportPropertyChanged("BillingDocumentIsCancelled");
                OnBillingDocumentIsCancelledChanged();
            }
        }
        private Nullable<global::System.Boolean> _BillingDocumentIsCancelled;
        partial void OnBillingDocumentIsCancelledChanging(Nullable<global::System.Boolean> value);
        partial void OnBillingDocumentIsCancelledChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CancelledBillingDocument
        {
            get
            {
                return _CancelledBillingDocument;
            }
            set
            {
                OnCancelledBillingDocumentChanging(value);
                ReportPropertyChanging("CancelledBillingDocument");
                _CancelledBillingDocument = StructuralObject.SetValidValue(value, true, "CancelledBillingDocument");
                ReportPropertyChanged("CancelledBillingDocument");
                OnCancelledBillingDocumentChanged();
            }
        }
        private global::System.String _CancelledBillingDocument;
        partial void OnCancelledBillingDocumentChanging(global::System.String value);
        partial void OnCancelledBillingDocumentChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForeignTrade
        {
            get
            {
                return _ForeignTrade;
            }
            set
            {
                OnForeignTradeChanging(value);
                ReportPropertyChanging("ForeignTrade");
                _ForeignTrade = StructuralObject.SetValidValue(value, true, "ForeignTrade");
                ReportPropertyChanged("ForeignTrade");
                OnForeignTradeChanged();
            }
        }
        private global::System.String _ForeignTrade;
        partial void OnForeignTradeChanging(global::System.String value);
        partial void OnForeignTradeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountingPostingStatus
        {
            get
            {
                return _AccountingPostingStatus;
            }
            set
            {
                OnAccountingPostingStatusChanging(value);
                ReportPropertyChanging("AccountingPostingStatus");
                _AccountingPostingStatus = StructuralObject.SetValidValue(value, true, "AccountingPostingStatus");
                ReportPropertyChanged("AccountingPostingStatus");
                OnAccountingPostingStatusChanged();
            }
        }
        private global::System.String _AccountingPostingStatus;
        partial void OnAccountingPostingStatusChanging(global::System.String value);
        partial void OnAccountingPostingStatusChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingDocCombinationCriteria
        {
            get
            {
                return _BillingDocCombinationCriteria;
            }
            set
            {
                OnBillingDocCombinationCriteriaChanging(value);
                ReportPropertyChanging("BillingDocCombinationCriteria");
                _BillingDocCombinationCriteria = StructuralObject.SetValidValue(value, true, "BillingDocCombinationCriteria");
                ReportPropertyChanged("BillingDocCombinationCriteria");
                OnBillingDocCombinationCriteriaChanged();
            }
        }
        private global::System.String _BillingDocCombinationCriteria;
        partial void OnBillingDocCombinationCriteriaChanging(global::System.String value);
        partial void OnBillingDocCombinationCriteriaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerRebateAgreement
        {
            get
            {
                return _CustomerRebateAgreement;
            }
            set
            {
                OnCustomerRebateAgreementChanging(value);
                ReportPropertyChanging("CustomerRebateAgreement");
                _CustomerRebateAgreement = StructuralObject.SetValidValue(value, true, "CustomerRebateAgreement");
                ReportPropertyChanged("CustomerRebateAgreement");
                OnCustomerRebateAgreementChanged();
            }
        }
        private global::System.String _CustomerRebateAgreement;
        partial void OnCustomerRebateAgreementChanging(global::System.String value);
        partial void OnCustomerRebateAgreementChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditControlArea
        {
            get
            {
                return _CreditControlArea;
            }
            set
            {
                OnCreditControlAreaChanging(value);
                ReportPropertyChanging("CreditControlArea");
                _CreditControlArea = StructuralObject.SetValidValue(value, true, "CreditControlArea");
                ReportPropertyChanged("CreditControlArea");
                OnCreditControlAreaChanged();
            }
        }
        private global::System.String _CreditControlArea;
        partial void OnCreditControlAreaChanging(global::System.String value);
        partial void OnCreditControlAreaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _County;
            }
            set
            {
                OnCountyChanging(value);
                ReportPropertyChanging("County");
                _County = StructuralObject.SetValidValue(value, true, "County");
                ReportPropertyChanged("County");
                OnCountyChanged();
            }
        }
        private global::System.String _County;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityCode
        {
            get
            {
                return _CityCode;
            }
            set
            {
                OnCityCodeChanging(value);
                ReportPropertyChanging("CityCode");
                _CityCode = StructuralObject.SetValidValue(value, true, "CityCode");
                ReportPropertyChanged("CityCode");
                OnCityCodeChanged();
            }
        }
        private global::System.String _CityCode;
        partial void OnCityCodeChanging(global::System.String value);
        partial void OnCityCodeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true, "Country");
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerGroup
        {
            get
            {
                return _CustomerGroup;
            }
            set
            {
                OnCustomerGroupChanging(value);
                ReportPropertyChanging("CustomerGroup");
                _CustomerGroup = StructuralObject.SetValidValue(value, true, "CustomerGroup");
                ReportPropertyChanged("CustomerGroup");
                OnCustomerGroupChanged();
            }
        }
        private global::System.String _CustomerGroup;
        partial void OnCustomerGroupChanging(global::System.String value);
        partial void OnCustomerGroupChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DunningKey
        {
            get
            {
                return _DunningKey;
            }
            set
            {
                OnDunningKeyChanging(value);
                ReportPropertyChanging("DunningKey");
                _DunningKey = StructuralObject.SetValidValue(value, true, "DunningKey");
                ReportPropertyChanged("DunningKey");
                OnDunningKeyChanged();
            }
        }
        private global::System.String _DunningKey;
        partial void OnDunningKeyChanging(global::System.String value);
        partial void OnDunningKeyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DunningBlockingReason
        {
            get
            {
                return _DunningBlockingReason;
            }
            set
            {
                OnDunningBlockingReasonChanging(value);
                ReportPropertyChanging("DunningBlockingReason");
                _DunningBlockingReason = StructuralObject.SetValidValue(value, true, "DunningBlockingReason");
                ReportPropertyChanged("DunningBlockingReason");
                OnDunningBlockingReasonChanged();
            }
        }
        private global::System.String _DunningBlockingReason;
        partial void OnDunningBlockingReasonChanging(global::System.String value);
        partial void OnDunningBlockingReasonChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerPriceGroup
        {
            get
            {
                return _CustomerPriceGroup;
            }
            set
            {
                OnCustomerPriceGroupChanging(value);
                ReportPropertyChanging("CustomerPriceGroup");
                _CustomerPriceGroup = StructuralObject.SetValidValue(value, true, "CustomerPriceGroup");
                ReportPropertyChanged("CustomerPriceGroup");
                OnCustomerPriceGroupChanged();
            }
        }
        private global::System.String _CustomerPriceGroup;
        partial void OnCustomerPriceGroupChanging(global::System.String value);
        partial void OnCustomerPriceGroupChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DunningArea
        {
            get
            {
                return _DunningArea;
            }
            set
            {
                OnDunningAreaChanging(value);
                ReportPropertyChanging("DunningArea");
                _DunningArea = StructuralObject.SetValidValue(value, true, "DunningArea");
                ReportPropertyChanged("DunningArea");
                OnDunningAreaChanged();
            }
        }
        private global::System.String _DunningArea;
        partial void OnDunningAreaChanging(global::System.String value);
        partial void OnDunningAreaChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssignmentReference
        {
            get
            {
                return _AssignmentReference;
            }
            set
            {
                OnAssignmentReferenceChanging(value);
                ReportPropertyChanging("AssignmentReference");
                _AssignmentReference = StructuralObject.SetValidValue(value, true, "AssignmentReference");
                ReportPropertyChanged("AssignmentReference");
                OnAssignmentReferenceChanged();
            }
        }
        private global::System.String _AssignmentReference;
        partial void OnAssignmentReferenceChanging(global::System.String value);
        partial void OnAssignmentReferenceChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocumentReferenceID
        {
            get
            {
                return _DocumentReferenceID;
            }
            set
            {
                OnDocumentReferenceIDChanging(value);
                ReportPropertyChanging("DocumentReferenceID");
                _DocumentReferenceID = StructuralObject.SetValidValue(value, true, "DocumentReferenceID");
                ReportPropertyChanged("DocumentReferenceID");
                OnDocumentReferenceIDChanged();
            }
        }
        private global::System.String _DocumentReferenceID;
        partial void OnDocumentReferenceIDChanging(global::System.String value);
        partial void OnDocumentReferenceIDChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExchangeRateType
        {
            get
            {
                return _ExchangeRateType;
            }
            set
            {
                OnExchangeRateTypeChanging(value);
                ReportPropertyChanging("ExchangeRateType");
                _ExchangeRateType = StructuralObject.SetValidValue(value, true, "ExchangeRateType");
                ReportPropertyChanged("ExchangeRateType");
                OnExchangeRateTypeChanged();
            }
        }
        private global::System.String _ExchangeRateType;
        partial void OnExchangeRateTypeChanging(global::System.String value);
        partial void OnExchangeRateTypeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExchangeRateDate
        {
            get
            {
                return _ExchangeRateDate;
            }
            set
            {
                OnExchangeRateDateChanging(value);
                ReportPropertyChanging("ExchangeRateDate");
                _ExchangeRateDate = StructuralObject.SetValidValue(value, "ExchangeRateDate");
                ReportPropertyChanged("ExchangeRateDate");
                OnExchangeRateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExchangeRateDate;
        partial void OnExchangeRateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExchangeRateDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HierarchyTypePricing
        {
            get
            {
                return _HierarchyTypePricing;
            }
            set
            {
                OnHierarchyTypePricingChanging(value);
                ReportPropertyChanging("HierarchyTypePricing");
                _HierarchyTypePricing = StructuralObject.SetValidValue(value, true, "HierarchyTypePricing");
                ReportPropertyChanged("HierarchyTypePricing");
                OnHierarchyTypePricingChanged();
            }
        }
        private global::System.String _HierarchyTypePricing;
        partial void OnHierarchyTypePricingChanging(global::System.String value);
        partial void OnHierarchyTypePricingChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification1
        {
            get
            {
                return _CustomerTaxClassification1;
            }
            set
            {
                OnCustomerTaxClassification1Changing(value);
                ReportPropertyChanging("CustomerTaxClassification1");
                _CustomerTaxClassification1 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification1");
                ReportPropertyChanged("CustomerTaxClassification1");
                OnCustomerTaxClassification1Changed();
            }
        }
        private global::System.String _CustomerTaxClassification1;
        partial void OnCustomerTaxClassification1Changing(global::System.String value);
        partial void OnCustomerTaxClassification1Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification2
        {
            get
            {
                return _CustomerTaxClassification2;
            }
            set
            {
                OnCustomerTaxClassification2Changing(value);
                ReportPropertyChanging("CustomerTaxClassification2");
                _CustomerTaxClassification2 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification2");
                ReportPropertyChanged("CustomerTaxClassification2");
                OnCustomerTaxClassification2Changed();
            }
        }
        private global::System.String _CustomerTaxClassification2;
        partial void OnCustomerTaxClassification2Changing(global::System.String value);
        partial void OnCustomerTaxClassification2Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification3
        {
            get
            {
                return _CustomerTaxClassification3;
            }
            set
            {
                OnCustomerTaxClassification3Changing(value);
                ReportPropertyChanging("CustomerTaxClassification3");
                _CustomerTaxClassification3 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification3");
                ReportPropertyChanged("CustomerTaxClassification3");
                OnCustomerTaxClassification3Changed();
            }
        }
        private global::System.String _CustomerTaxClassification3;
        partial void OnCustomerTaxClassification3Changing(global::System.String value);
        partial void OnCustomerTaxClassification3Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification4
        {
            get
            {
                return _CustomerTaxClassification4;
            }
            set
            {
                OnCustomerTaxClassification4Changing(value);
                ReportPropertyChanging("CustomerTaxClassification4");
                _CustomerTaxClassification4 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification4");
                ReportPropertyChanged("CustomerTaxClassification4");
                OnCustomerTaxClassification4Changed();
            }
        }
        private global::System.String _CustomerTaxClassification4;
        partial void OnCustomerTaxClassification4Changing(global::System.String value);
        partial void OnCustomerTaxClassification4Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification5
        {
            get
            {
                return _CustomerTaxClassification5;
            }
            set
            {
                OnCustomerTaxClassification5Changing(value);
                ReportPropertyChanging("CustomerTaxClassification5");
                _CustomerTaxClassification5 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification5");
                ReportPropertyChanged("CustomerTaxClassification5");
                OnCustomerTaxClassification5Changed();
            }
        }
        private global::System.String _CustomerTaxClassification5;
        partial void OnCustomerTaxClassification5Changing(global::System.String value);
        partial void OnCustomerTaxClassification5Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification6
        {
            get
            {
                return _CustomerTaxClassification6;
            }
            set
            {
                OnCustomerTaxClassification6Changing(value);
                ReportPropertyChanging("CustomerTaxClassification6");
                _CustomerTaxClassification6 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification6");
                ReportPropertyChanged("CustomerTaxClassification6");
                OnCustomerTaxClassification6Changed();
            }
        }
        private global::System.String _CustomerTaxClassification6;
        partial void OnCustomerTaxClassification6Changing(global::System.String value);
        partial void OnCustomerTaxClassification6Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification7
        {
            get
            {
                return _CustomerTaxClassification7;
            }
            set
            {
                OnCustomerTaxClassification7Changing(value);
                ReportPropertyChanging("CustomerTaxClassification7");
                _CustomerTaxClassification7 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification7");
                ReportPropertyChanged("CustomerTaxClassification7");
                OnCustomerTaxClassification7Changed();
            }
        }
        private global::System.String _CustomerTaxClassification7;
        partial void OnCustomerTaxClassification7Changing(global::System.String value);
        partial void OnCustomerTaxClassification7Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification8
        {
            get
            {
                return _CustomerTaxClassification8;
            }
            set
            {
                OnCustomerTaxClassification8Changing(value);
                ReportPropertyChanging("CustomerTaxClassification8");
                _CustomerTaxClassification8 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification8");
                ReportPropertyChanged("CustomerTaxClassification8");
                OnCustomerTaxClassification8Changed();
            }
        }
        private global::System.String _CustomerTaxClassification8;
        partial void OnCustomerTaxClassification8Changing(global::System.String value);
        partial void OnCustomerTaxClassification8Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerTaxClassification9
        {
            get
            {
                return _CustomerTaxClassification9;
            }
            set
            {
                OnCustomerTaxClassification9Changing(value);
                ReportPropertyChanging("CustomerTaxClassification9");
                _CustomerTaxClassification9 = StructuralObject.SetValidValue(value, true, "CustomerTaxClassification9");
                ReportPropertyChanged("CustomerTaxClassification9");
                OnCustomerTaxClassification9Changed();
            }
        }
        private global::System.String _CustomerTaxClassification9;
        partial void OnCustomerTaxClassification9Changing(global::System.String value);
        partial void OnCustomerTaxClassification9Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AcctgExchangeRateIsIndrctQtan
        {
            get
            {
                return _AcctgExchangeRateIsIndrctQtan;
            }
            set
            {
                OnAcctgExchangeRateIsIndrctQtanChanging(value);
                ReportPropertyChanging("AcctgExchangeRateIsIndrctQtan");
                _AcctgExchangeRateIsIndrctQtan = StructuralObject.SetValidValue(value, "AcctgExchangeRateIsIndrctQtan");
                ReportPropertyChanged("AcctgExchangeRateIsIndrctQtan");
                OnAcctgExchangeRateIsIndrctQtanChanged();
            }
        }
        private Nullable<global::System.Boolean> _AcctgExchangeRateIsIndrctQtan;
        partial void OnAcctgExchangeRateIsIndrctQtanChanging(Nullable<global::System.Boolean> value);
        partial void OnAcctgExchangeRateIsIndrctQtanChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AbsltAccountingExchangeRate
        {
            get
            {
                return _AbsltAccountingExchangeRate;
            }
            set
            {
                OnAbsltAccountingExchangeRateChanging(value);
                ReportPropertyChanging("AbsltAccountingExchangeRate");
                _AbsltAccountingExchangeRate = StructuralObject.SetValidValue(value, "AbsltAccountingExchangeRate");
                ReportPropertyChanged("AbsltAccountingExchangeRate");
                OnAbsltAccountingExchangeRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _AbsltAccountingExchangeRate;
        partial void OnAbsltAccountingExchangeRateChanging(Nullable<global::System.Decimal> value);
        partial void OnAbsltAccountingExchangeRateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AccountingExchangeRateIsSet
        {
            get
            {
                return _AccountingExchangeRateIsSet;
            }
            set
            {
                OnAccountingExchangeRateIsSetChanging(value);
                ReportPropertyChanging("AccountingExchangeRateIsSet");
                _AccountingExchangeRateIsSet = StructuralObject.SetValidValue(value, "AccountingExchangeRateIsSet");
                ReportPropertyChanged("AccountingExchangeRateIsSet");
                OnAccountingExchangeRateIsSetChanged();
            }
        }
        private Nullable<global::System.Boolean> _AccountingExchangeRateIsSet;
        partial void OnAccountingExchangeRateIsSetChanging(Nullable<global::System.Boolean> value);
        partial void OnAccountingExchangeRateIsSetChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerAccountAssignmentGroup
        {
            get
            {
                return _CustomerAccountAssignmentGroup;
            }
            set
            {
                OnCustomerAccountAssignmentGroupChanging(value);
                ReportPropertyChanging("CustomerAccountAssignmentGroup");
                _CustomerAccountAssignmentGroup = StructuralObject.SetValidValue(value, true, "CustomerAccountAssignmentGroup");
                ReportPropertyChanged("CustomerAccountAssignmentGroup");
                OnCustomerAccountAssignmentGroupChanged();
            }
        }
        private global::System.String _CustomerAccountAssignmentGroup;
        partial void OnCustomerAccountAssignmentGroupChanging(global::System.String value);
        partial void OnCustomerAccountAssignmentGroupChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncotermsClassification
        {
            get
            {
                return _IncotermsClassification;
            }
            set
            {
                OnIncotermsClassificationChanging(value);
                ReportPropertyChanging("IncotermsClassification");
                _IncotermsClassification = StructuralObject.SetValidValue(value, true, "IncotermsClassification");
                ReportPropertyChanged("IncotermsClassification");
                OnIncotermsClassificationChanged();
            }
        }
        private global::System.String _IncotermsClassification;
        partial void OnIncotermsClassificationChanging(global::System.String value);
        partial void OnIncotermsClassificationChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountingDocument
        {
            get
            {
                return _AccountingDocument;
            }
            set
            {
                OnAccountingDocumentChanging(value);
                ReportPropertyChanging("AccountingDocument");
                _AccountingDocument = StructuralObject.SetValidValue(value, true, "AccountingDocument");
                ReportPropertyChanged("AccountingDocument");
                OnAccountingDocumentChanged();
            }
        }
        private global::System.String _AccountingDocument;
        partial void OnAccountingDocumentChanging(global::System.String value);
        partial void OnAccountingDocumentChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncotermsLocation1
        {
            get
            {
                return _IncotermsLocation1;
            }
            set
            {
                OnIncotermsLocation1Changing(value);
                ReportPropertyChanging("IncotermsLocation1");
                _IncotermsLocation1 = StructuralObject.SetValidValue(value, true, "IncotermsLocation1");
                ReportPropertyChanged("IncotermsLocation1");
                OnIncotermsLocation1Changed();
            }
        }
        private global::System.String _IncotermsLocation1;
        partial void OnIncotermsLocation1Changing(global::System.String value);
        partial void OnIncotermsLocation1Changed();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FiscalYear
        {
            get
            {
                return _FiscalYear;
            }
            set
            {
                OnFiscalYearChanging(value);
                ReportPropertyChanging("FiscalYear");
                _FiscalYear = StructuralObject.SetValidValue(value, true, "FiscalYear");
                ReportPropertyChanged("FiscalYear");
                OnFiscalYearChanged();
            }
        }
        private global::System.String _FiscalYear;
        partial void OnFiscalYearChanging(global::System.String value);
        partial void OnFiscalYearChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCode
        {
            get
            {
                return _CompanyCode;
            }
            set
            {
                OnCompanyCodeChanging(value);
                ReportPropertyChanging("CompanyCode");
                _CompanyCode = StructuralObject.SetValidValue(value, true, "CompanyCode");
                ReportPropertyChanged("CompanyCode");
                OnCompanyCodeChanged();
            }
        }
        private global::System.String _CompanyCode;
        partial void OnCompanyCodeChanging(global::System.String value);
        partial void OnCompanyCodeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContractAccount
        {
            get
            {
                return _ContractAccount;
            }
            set
            {
                OnContractAccountChanging(value);
                ReportPropertyChanging("ContractAccount");
                _ContractAccount = StructuralObject.SetValidValue(value, true, "ContractAccount");
                ReportPropertyChanged("ContractAccount");
                OnContractAccountChanged();
            }
        }
        private global::System.String _ContractAccount;
        partial void OnContractAccountChanging(global::System.String value);
        partial void OnContractAccountChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerPaymentTerms
        {
            get
            {
                return _CustomerPaymentTerms;
            }
            set
            {
                OnCustomerPaymentTermsChanging(value);
                ReportPropertyChanging("CustomerPaymentTerms");
                _CustomerPaymentTerms = StructuralObject.SetValidValue(value, true, "CustomerPaymentTerms");
                ReportPropertyChanged("CustomerPaymentTerms");
                OnCustomerPaymentTermsChanged();
            }
        }
        private global::System.String _CustomerPaymentTerms;
        partial void OnCustomerPaymentTermsChanging(global::System.String value);
        partial void OnCustomerPaymentTermsChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdditionalValueDays
        {
            get
            {
                return _AdditionalValueDays;
            }
            set
            {
                OnAdditionalValueDaysChanging(value);
                ReportPropertyChanging("AdditionalValueDays");
                _AdditionalValueDays = StructuralObject.SetValidValue(value, true, "AdditionalValueDays");
                ReportPropertyChanged("AdditionalValueDays");
                OnAdditionalValueDaysChanged();
            }
        }
        private global::System.String _AdditionalValueDays;
        partial void OnAdditionalValueDaysChanging(global::System.String value);
        partial void OnAdditionalValueDaysChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FixedValueDate
        {
            get
            {
                return _FixedValueDate;
            }
            set
            {
                OnFixedValueDateChanging(value);
                ReportPropertyChanging("FixedValueDate");
                _FixedValueDate = StructuralObject.SetValidValue(value, "FixedValueDate");
                ReportPropertyChanged("FixedValueDate");
                OnFixedValueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FixedValueDate;
        partial void OnFixedValueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFixedValueDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatisticsCurrency
        {
            get
            {
                return _StatisticsCurrency;
            }
            set
            {
                OnStatisticsCurrencyChanging(value);
                ReportPropertyChanging("StatisticsCurrency");
                _StatisticsCurrency = StructuralObject.SetValidValue(value, true, "StatisticsCurrency");
                ReportPropertyChanged("StatisticsCurrency");
                OnStatisticsCurrencyChanged();
            }
        }
        private global::System.String _StatisticsCurrency;
        partial void OnStatisticsCurrencyChanging(global::System.String value);
        partial void OnStatisticsCurrencyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentReference
        {
            get
            {
                return _PaymentReference;
            }
            set
            {
                OnPaymentReferenceChanging(value);
                ReportPropertyChanging("PaymentReference");
                _PaymentReference = StructuralObject.SetValidValue(value, true, "PaymentReference");
                ReportPropertyChanged("PaymentReference");
                OnPaymentReferenceChanged();
            }
        }
        private global::System.String _PaymentReference;
        partial void OnPaymentReferenceChanging(global::System.String value);
        partial void OnPaymentReferenceChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastChangeDate
        {
            get
            {
                return _LastChangeDate;
            }
            set
            {
                OnLastChangeDateChanging(value);
                ReportPropertyChanging("LastChangeDate");
                _LastChangeDate = StructuralObject.SetValidValue(value, "LastChangeDate");
                ReportPropertyChanged("LastChangeDate");
                OnLastChangeDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastChangeDate;
        partial void OnLastChangeDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastChangeDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayerParty
        {
            get
            {
                return _PayerParty;
            }
            set
            {
                OnPayerPartyChanging(value);
                ReportPropertyChanging("PayerParty");
                _PayerParty = StructuralObject.SetValidValue(value, true, "PayerParty");
                ReportPropertyChanged("PayerParty");
                OnPayerPartyChanged();
            }
        }
        private global::System.String _PayerParty;
        partial void OnPayerPartyChanging(global::System.String value);
        partial void OnPayerPartyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastChangeDateTime
        {
            get
            {
                return _LastChangeDateTime;
            }
            set
            {
                OnLastChangeDateTimeChanging(value);
                ReportPropertyChanging("LastChangeDateTime");
                _LastChangeDateTime = StructuralObject.SetValidValue(value, "LastChangeDateTime");
                ReportPropertyChanged("LastChangeDateTime");
                OnLastChangeDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastChangeDateTime;
        partial void OnLastChangeDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastChangeDateTimeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncotermsTransferLocation
        {
            get
            {
                return _IncotermsTransferLocation;
            }
            set
            {
                OnIncotermsTransferLocationChanging(value);
                ReportPropertyChanging("IncotermsTransferLocation");
                _IncotermsTransferLocation = StructuralObject.SetValidValue(value, true, "IncotermsTransferLocation");
                ReportPropertyChanged("IncotermsTransferLocation");
                OnIncotermsTransferLocationChanged();
            }
        }
        private global::System.String _IncotermsTransferLocation;
        partial void OnIncotermsTransferLocationChanging(global::System.String value);
        partial void OnIncotermsTransferLocationChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncotermsVersion
        {
            get
            {
                return _IncotermsVersion;
            }
            set
            {
                OnIncotermsVersionChanging(value);
                ReportPropertyChanging("IncotermsVersion");
                _IncotermsVersion = StructuralObject.SetValidValue(value, true, "IncotermsVersion");
                ReportPropertyChanged("IncotermsVersion");
                OnIncotermsVersionChanged();
            }
        }
        private global::System.String _IncotermsVersion;
        partial void OnIncotermsVersionChanging(global::System.String value);
        partial void OnIncotermsVersionChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverallPricingIncompletionSts
        {
            get
            {
                return _OverallPricingIncompletionSts;
            }
            set
            {
                OnOverallPricingIncompletionStsChanging(value);
                ReportPropertyChanging("OverallPricingIncompletionSts");
                _OverallPricingIncompletionSts = StructuralObject.SetValidValue(value, true, "OverallPricingIncompletionSts");
                ReportPropertyChanged("OverallPricingIncompletionSts");
                OnOverallPricingIncompletionStsChanged();
            }
        }
        private global::System.String _OverallPricingIncompletionSts;
        partial void OnOverallPricingIncompletionStsChanging(global::System.String value);
        partial void OnOverallPricingIncompletionStsChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OvrlItmGeneralIncompletionSts
        {
            get
            {
                return _OvrlItmGeneralIncompletionSts;
            }
            set
            {
                OnOvrlItmGeneralIncompletionStsChanging(value);
                ReportPropertyChanging("OvrlItmGeneralIncompletionSts");
                _OvrlItmGeneralIncompletionSts = StructuralObject.SetValidValue(value, true, "OvrlItmGeneralIncompletionSts");
                ReportPropertyChanged("OvrlItmGeneralIncompletionSts");
                OnOvrlItmGeneralIncompletionStsChanged();
            }
        }
        private global::System.String _OvrlItmGeneralIncompletionSts;
        partial void OnOvrlItmGeneralIncompletionStsChanging(global::System.String value);
        partial void OnOvrlItmGeneralIncompletionStsChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsEUTriangularDeal
        {
            get
            {
                return _IsEUTriangularDeal;
            }
            set
            {
                OnIsEUTriangularDealChanging(value);
                ReportPropertyChanging("IsEUTriangularDeal");
                _IsEUTriangularDeal = StructuralObject.SetValidValue(value, "IsEUTriangularDeal");
                ReportPropertyChanged("IsEUTriangularDeal");
                OnIsEUTriangularDealChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsEUTriangularDeal;
        partial void OnIsEUTriangularDealChanging(Nullable<global::System.Boolean> value);
        partial void OnIsEUTriangularDealChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceListStatus
        {
            get
            {
                return _InvoiceListStatus;
            }
            set
            {
                OnInvoiceListStatusChanging(value);
                ReportPropertyChanging("InvoiceListStatus");
                _InvoiceListStatus = StructuralObject.SetValidValue(value, true, "InvoiceListStatus");
                ReportPropertyChanged("InvoiceListStatus");
                OnInvoiceListStatusChanged();
            }
        }
        private global::System.String _InvoiceListStatus;
        partial void OnInvoiceListStatusChanging(global::System.String value);
        partial void OnInvoiceListStatusChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LogicalSystem
        {
            get
            {
                return _LogicalSystem;
            }
            set
            {
                OnLogicalSystemChanging(value);
                ReportPropertyChanging("LogicalSystem");
                _LogicalSystem = StructuralObject.SetValidValue(value, true, "LogicalSystem");
                ReportPropertyChanged("LogicalSystem");
                OnLogicalSystemChanged();
            }
        }
        private global::System.String _LogicalSystem;
        partial void OnLogicalSystemChanging(global::System.String value);
        partial void OnLogicalSystemChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsExportDelivery
        {
            get
            {
                return _IsExportDelivery;
            }
            set
            {
                OnIsExportDeliveryChanging(value);
                ReportPropertyChanging("IsExportDelivery");
                _IsExportDelivery = StructuralObject.SetValidValue(value, true, "IsExportDelivery");
                ReportPropertyChanged("IsExportDelivery");
                OnIsExportDeliveryChanged();
            }
        }
        private global::System.String _IsExportDelivery;
        partial void OnIsExportDeliveryChanging(global::System.String value);
        partial void OnIsExportDeliveryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverallBillingStatus
        {
            get
            {
                return _OverallBillingStatus;
            }
            set
            {
                OnOverallBillingStatusChanging(value);
                ReportPropertyChanging("OverallBillingStatus");
                _OverallBillingStatus = StructuralObject.SetValidValue(value, true, "OverallBillingStatus");
                ReportPropertyChanged("OverallBillingStatus");
                OnOverallBillingStatusChanged();
            }
        }
        private global::System.String _OverallBillingStatus;
        partial void OnOverallBillingStatusChanging(global::System.String value);
        partial void OnOverallBillingStatusChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverallSDProcessStatus
        {
            get
            {
                return _OverallSDProcessStatus;
            }
            set
            {
                OnOverallSDProcessStatusChanging(value);
                ReportPropertyChanging("OverallSDProcessStatus");
                _OverallSDProcessStatus = StructuralObject.SetValidValue(value, true, "OverallSDProcessStatus");
                ReportPropertyChanged("OverallSDProcessStatus");
                OnOverallSDProcessStatusChanged();
            }
        }
        private global::System.String _OverallSDProcessStatus;
        partial void OnOverallSDProcessStatusChanging(global::System.String value);
        partial void OnOverallSDProcessStatusChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ManualInvoiceMaintIsRelevant
        {
            get
            {
                return _ManualInvoiceMaintIsRelevant;
            }
            set
            {
                OnManualInvoiceMaintIsRelevantChanging(value);
                ReportPropertyChanging("ManualInvoiceMaintIsRelevant");
                _ManualInvoiceMaintIsRelevant = StructuralObject.SetValidValue(value, "ManualInvoiceMaintIsRelevant");
                ReportPropertyChanged("ManualInvoiceMaintIsRelevant");
                OnManualInvoiceMaintIsRelevantChanged();
            }
        }
        private Nullable<global::System.Boolean> _ManualInvoiceMaintIsRelevant;
        partial void OnManualInvoiceMaintIsRelevantChanging(Nullable<global::System.Boolean> value);
        partial void OnManualInvoiceMaintIsRelevantChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsIntrastatReportingRelevant
        {
            get
            {
                return _IsIntrastatReportingRelevant;
            }
            set
            {
                OnIsIntrastatReportingRelevantChanging(value);
                ReportPropertyChanging("IsIntrastatReportingRelevant");
                _IsIntrastatReportingRelevant = StructuralObject.SetValidValue(value, "IsIntrastatReportingRelevant");
                ReportPropertyChanged("IsIntrastatReportingRelevant");
                OnIsIntrastatReportingRelevantChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsIntrastatReportingRelevant;
        partial void OnIsIntrastatReportingRelevantChanging(Nullable<global::System.Boolean> value);
        partial void OnIsIntrastatReportingRelevantChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalFinancialDocument
        {
            get
            {
                return _InternalFinancialDocument;
            }
            set
            {
                OnInternalFinancialDocumentChanging(value);
                ReportPropertyChanging("InternalFinancialDocument");
                _InternalFinancialDocument = StructuralObject.SetValidValue(value, true, "InternalFinancialDocument");
                ReportPropertyChanged("InternalFinancialDocument");
                OnInternalFinancialDocumentChanged();
            }
        }
        private global::System.String _InternalFinancialDocument;
        partial void OnInternalFinancialDocumentChanging(global::System.String value);
        partial void OnInternalFinancialDocumentChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRelevantForAccrual
        {
            get
            {
                return _IsRelevantForAccrual;
            }
            set
            {
                OnIsRelevantForAccrualChanging(value);
                ReportPropertyChanging("IsRelevantForAccrual");
                _IsRelevantForAccrual = StructuralObject.SetValidValue(value, "IsRelevantForAccrual");
                ReportPropertyChanged("IsRelevantForAccrual");
                OnIsRelevantForAccrualChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRelevantForAccrual;
        partial void OnIsRelevantForAccrualChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRelevantForAccrualChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsIntrastatReportingExcluded
        {
            get
            {
                return _IsIntrastatReportingExcluded;
            }
            set
            {
                OnIsIntrastatReportingExcludedChanging(value);
                ReportPropertyChanging("IsIntrastatReportingExcluded");
                _IsIntrastatReportingExcluded = StructuralObject.SetValidValue(value, "IsIntrastatReportingExcluded");
                ReportPropertyChanged("IsIntrastatReportingExcluded");
                OnIsIntrastatReportingExcludedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsIntrastatReportingExcluded;
        partial void OnIsIntrastatReportingExcludedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsIntrastatReportingExcludedChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PartnerCompany
        {
            get
            {
                return _PartnerCompany;
            }
            set
            {
                OnPartnerCompanyChanging(value);
                ReportPropertyChanging("PartnerCompany");
                _PartnerCompany = StructuralObject.SetValidValue(value, true, "PartnerCompany");
                ReportPropertyChanged("PartnerCompany");
                OnPartnerCompanyChanged();
            }
        }
        private global::System.String _PartnerCompany;
        partial void OnPartnerCompanyChanging(global::System.String value);
        partial void OnPartnerCompanyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentMethod
        {
            get
            {
                return _PaymentMethod;
            }
            set
            {
                OnPaymentMethodChanging(value);
                ReportPropertyChanging("PaymentMethod");
                _PaymentMethod = StructuralObject.SetValidValue(value, true, "PaymentMethod");
                ReportPropertyChanged("PaymentMethod");
                OnPaymentMethodChanged();
            }
        }
        private global::System.String _PaymentMethod;
        partial void OnPaymentMethodChanging(global::System.String value);
        partial void OnPaymentMethodChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VATRegistration
        {
            get
            {
                return _VATRegistration;
            }
            set
            {
                OnVATRegistrationChanging(value);
                ReportPropertyChanging("VATRegistration");
                _VATRegistration = StructuralObject.SetValidValue(value, true, "VATRegistration");
                ReportPropertyChanged("VATRegistration");
                OnVATRegistrationChanged();
            }
        }
        private global::System.String _VATRegistration;
        partial void OnVATRegistrationChanging(global::System.String value);
        partial void OnVATRegistrationChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PurchaseOrderByCustomer
        {
            get
            {
                return _PurchaseOrderByCustomer;
            }
            set
            {
                OnPurchaseOrderByCustomerChanging(value);
                ReportPropertyChanging("PurchaseOrderByCustomer");
                _PurchaseOrderByCustomer = StructuralObject.SetValidValue(value, true, "PurchaseOrderByCustomer");
                ReportPropertyChanged("PurchaseOrderByCustomer");
                OnPurchaseOrderByCustomerChanged();
            }
        }
        private global::System.String _PurchaseOrderByCustomer;
        partial void OnPurchaseOrderByCustomerChanging(global::System.String value);
        partial void OnPurchaseOrderByCustomerChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PriceListType
        {
            get
            {
                return _PriceListType;
            }
            set
            {
                OnPriceListTypeChanging(value);
                ReportPropertyChanging("PriceListType");
                _PriceListType = StructuralObject.SetValidValue(value, true, "PriceListType");
                ReportPropertyChanged("PriceListType");
                OnPriceListTypeChanged();
            }
        }
        private global::System.String _PriceListType;
        partial void OnPriceListTypeChanging(global::System.String value);
        partial void OnPriceListTypeChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalesOrganization
        {
            get
            {
                return _SalesOrganization;
            }
            set
            {
                OnSalesOrganizationChanging(value);
                ReportPropertyChanging("SalesOrganization");
                _SalesOrganization = StructuralObject.SetValidValue(value, true, "SalesOrganization");
                ReportPropertyChanged("SalesOrganization");
                OnSalesOrganizationChanged();
            }
        }
        private global::System.String _SalesOrganization;
        partial void OnSalesOrganizationChanging(global::System.String value);
        partial void OnSalesOrganizationChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalesDistrict
        {
            get
            {
                return _SalesDistrict;
            }
            set
            {
                OnSalesDistrictChanging(value);
                ReportPropertyChanging("SalesDistrict");
                _SalesDistrict = StructuralObject.SetValidValue(value, true, "SalesDistrict");
                ReportPropertyChanged("SalesDistrict");
                OnSalesDistrictChanged();
            }
        }
        private global::System.String _SalesDistrict;
        partial void OnSalesDistrictChanging(global::System.String value);
        partial void OnSalesDistrictChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEPAMandate
        {
            get
            {
                return _SEPAMandate;
            }
            set
            {
                OnSEPAMandateChanging(value);
                ReportPropertyChanging("SEPAMandate");
                _SEPAMandate = StructuralObject.SetValidValue(value, true, "SEPAMandate");
                ReportPropertyChanged("SEPAMandate");
                OnSEPAMandateChanged();
            }
        }
        private global::System.String _SEPAMandate;
        partial void OnSEPAMandateChanging(global::System.String value);
        partial void OnSEPAMandateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDDocumentCategory
        {
            get
            {
                return _SDDocumentCategory;
            }
            set
            {
                OnSDDocumentCategoryChanging(value);
                ReportPropertyChanging("SDDocumentCategory");
                _SDDocumentCategory = StructuralObject.SetValidValue(value, true, "SDDocumentCategory");
                ReportPropertyChanged("SDDocumentCategory");
                OnSDDocumentCategoryChanged();
            }
        }
        private global::System.String _SDDocumentCategory;
        partial void OnSDDocumentCategoryChanging(global::System.String value);
        partial void OnSDDocumentCategoryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDPricingProcedure
        {
            get
            {
                return _SDPricingProcedure;
            }
            set
            {
                OnSDPricingProcedureChanging(value);
                ReportPropertyChanging("SDPricingProcedure");
                _SDPricingProcedure = StructuralObject.SetValidValue(value, true, "SDPricingProcedure");
                ReportPropertyChanged("SDPricingProcedure");
                OnSDPricingProcedureChanged();
            }
        }
        private global::System.String _SDPricingProcedure;
        partial void OnSDPricingProcedureChanging(global::System.String value);
        partial void OnSDPricingProcedureChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true, "Region");
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalGrossAmount
        {
            get
            {
                return _TotalGrossAmount;
            }
            set
            {
                OnTotalGrossAmountChanging(value);
                ReportPropertyChanging("TotalGrossAmount");
                _TotalGrossAmount = StructuralObject.SetValidValue(value, "TotalGrossAmount");
                ReportPropertyChanged("TotalGrossAmount");
                OnTotalGrossAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalGrossAmount;
        partial void OnTotalGrossAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalGrossAmountChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalNetAmount
        {
            get
            {
                return _TotalNetAmount;
            }
            set
            {
                OnTotalNetAmountChanging(value);
                ReportPropertyChanging("TotalNetAmount");
                _TotalNetAmount = StructuralObject.SetValidValue(value, "TotalNetAmount");
                ReportPropertyChanged("TotalNetAmount");
                OnTotalNetAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalNetAmount;
        partial void OnTotalNetAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalNetAmountChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoldToParty
        {
            get
            {
                return _SoldToParty;
            }
            set
            {
                OnSoldToPartyChanging(value);
                ReportPropertyChanging("SoldToParty");
                _SoldToParty = StructuralObject.SetValidValue(value, true, "SoldToParty");
                ReportPropertyChanged("SoldToParty");
                OnSoldToPartyChanged();
            }
        }
        private global::System.String _SoldToParty;
        partial void OnSoldToPartyChanging(global::System.String value);
        partial void OnSoldToPartyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalesDocumentCondition
        {
            get
            {
                return _SalesDocumentCondition;
            }
            set
            {
                OnSalesDocumentConditionChanging(value);
                ReportPropertyChanging("SalesDocumentCondition");
                _SalesDocumentCondition = StructuralObject.SetValidValue(value, true, "SalesDocumentCondition");
                ReportPropertyChanged("SalesDocumentCondition");
                OnSalesDocumentConditionChanged();
            }
        }
        private global::System.String _SalesDocumentCondition;
        partial void OnSalesDocumentConditionChanging(global::System.String value);
        partial void OnSalesDocumentConditionChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TaxAmount
        {
            get
            {
                return _TaxAmount;
            }
            set
            {
                OnTaxAmountChanging(value);
                ReportPropertyChanging("TaxAmount");
                _TaxAmount = StructuralObject.SetValidValue(value, "TaxAmount");
                ReportPropertyChanged("TaxAmount");
                OnTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TaxAmount;
        partial void OnTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTaxAmountChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShippingCondition
        {
            get
            {
                return _ShippingCondition;
            }
            set
            {
                OnShippingConditionChanging(value);
                ReportPropertyChanging("ShippingCondition");
                _ShippingCondition = StructuralObject.SetValidValue(value, true, "ShippingCondition");
                ReportPropertyChanged("ShippingCondition");
                OnShippingConditionChanged();
            }
        }
        private global::System.String _ShippingCondition;
        partial void OnShippingConditionChanging(global::System.String value);
        partial void OnShippingConditionChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxDepartureCountry
        {
            get
            {
                return _TaxDepartureCountry;
            }
            set
            {
                OnTaxDepartureCountryChanging(value);
                ReportPropertyChanging("TaxDepartureCountry");
                _TaxDepartureCountry = StructuralObject.SetValidValue(value, true, "TaxDepartureCountry");
                ReportPropertyChanged("TaxDepartureCountry");
                OnTaxDepartureCountryChanged();
            }
        }
        private global::System.String _TaxDepartureCountry;
        partial void OnTaxDepartureCountryChanging(global::System.String value);
        partial void OnTaxDepartureCountryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransactionCurrency
        {
            get
            {
                return _TransactionCurrency;
            }
            set
            {
                OnTransactionCurrencyChanging(value);
                ReportPropertyChanging("TransactionCurrency");
                _TransactionCurrency = StructuralObject.SetValidValue(value, true, "TransactionCurrency");
                ReportPropertyChanged("TransactionCurrency");
                OnTransactionCurrencyChanged();
            }
        }
        private global::System.String _TransactionCurrency;
        partial void OnTransactionCurrencyChanging(global::System.String value);
        partial void OnTransactionCurrencyChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VATRegistrationCountry
        {
            get
            {
                return _VATRegistrationCountry;
            }
            set
            {
                OnVATRegistrationCountryChanging(value);
                ReportPropertyChanging("VATRegistrationCountry");
                _VATRegistrationCountry = StructuralObject.SetValidValue(value, true, "VATRegistrationCountry");
                ReportPropertyChanged("VATRegistrationCountry");
                OnVATRegistrationCountryChanged();
            }
        }
        private global::System.String _VATRegistrationCountry;
        partial void OnVATRegistrationCountryChanging(global::System.String value);
        partial void OnVATRegistrationCountryChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VATRegistrationOrigin
        {
            get
            {
                return _VATRegistrationOrigin;
            }
            set
            {
                OnVATRegistrationOriginChanging(value);
                ReportPropertyChanging("VATRegistrationOrigin");
                _VATRegistrationOrigin = StructuralObject.SetValidValue(value, true, "VATRegistrationOrigin");
                ReportPropertyChanged("VATRegistrationOrigin");
                OnVATRegistrationOriginChanged();
            }
        }
        private global::System.String _VATRegistrationOrigin;
        partial void OnVATRegistrationOriginChanging(global::System.String value);
        partial void OnVATRegistrationOriginChanged();

        #endregion

    }

    #endregion

}
