//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArxivarSapIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class FE_PDF_Arxivar_CHECK
    {
        public string BillingDocument { get; set; }
        public string AccountingDocument { get; set; }
        public string FiscalYear { get; set; }
        public Nullable<System.DateTime> BillingDocumentDate { get; set; }
        public string SoldToParty { get; set; }
        public string BillingDocumentType { get; set; }
        public Nullable<decimal> TotalNetAmount { get; set; }
        public string VATRegistrationCountry { get; set; }
    }
}
