//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ArxivarSAPIntegration.MaterialDocumentGet {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaterialDocumentGetSOAP", Namespace="http://www.culligan.it/MaterialDocumentGet/")]
    public partial class MaterialDocumentGet : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallMaterialDocumentGetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MaterialDocumentGet() {
            this.Url = global::ArxivarSAPIntegration.Properties.Settings.Default.ArxivarSAPIntegration_MaterialDocumentGet_MaterialDocumentGet;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallMaterialDocumentGetCompletedEventHandler CallMaterialDocumentGetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.culligan.it/materialdocumentget", RequestElementName="MaterialDocumentGet", RequestNamespace="http://www.culligan.it/MaterialDocumentGet/", ResponseElementName="MaterialDocumentGetResponse", ResponseNamespace="http://www.culligan.it/MaterialDocumentGet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("A_MaterialDocumentItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("A_MaterialDocumentItemType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MaterialDocumentGetResponseA_MaterialDocumentItemType[] CallMaterialDocumentGet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LastRunDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string InvoiceType) {
            object[] results = this.Invoke("CallMaterialDocumentGet", new object[] {
                        LastRunDate,
                        InvoiceType});
            return ((MaterialDocumentGetResponseA_MaterialDocumentItemType[])(results[0]));
        }
        
        /// <remarks/>
        public void CallMaterialDocumentGetAsync(string LastRunDate, string InvoiceType) {
            this.CallMaterialDocumentGetAsync(LastRunDate, InvoiceType, null);
        }
        
        /// <remarks/>
        public void CallMaterialDocumentGetAsync(string LastRunDate, string InvoiceType, object userState) {
            if ((this.CallMaterialDocumentGetOperationCompleted == null)) {
                this.CallMaterialDocumentGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallMaterialDocumentGetOperationCompleted);
            }
            this.InvokeAsync("CallMaterialDocumentGet", new object[] {
                        LastRunDate,
                        InvoiceType}, this.CallMaterialDocumentGetOperationCompleted, userState);
        }
        
        private void OnCallMaterialDocumentGetOperationCompleted(object arg) {
            if ((this.CallMaterialDocumentGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallMaterialDocumentGetCompleted(this, new CallMaterialDocumentGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/MaterialDocumentGet/")]
    public partial class MaterialDocumentGetResponseA_MaterialDocumentItemType {
        
        private string[] materialDocumentField;
        
        private string[] materialDocumentItemField;
        
        private string[] materialDocumentYearField;
        
        private string[] materialField;
        
        private string[] plantField;
        
        private System.Nullable<bool>[] goodsMovementIsCancelledField;
        
        private string[] batchField;
        
        private string[] goodsMovementTypeField;
        
        private string[] purchaseOrderField;
        
        private string[] purchaseOrderItemField;
        
        private string[] goodsMovementRefDocTypeField;
        
        private string[] goodsMovementReasonCodeField;
        
        private string[] gLAccountField;
        
        private string[] materialDocumentItemTextField;
        
        private string[] fiscalYearField;
        
        private string[] supplierField;
        
        private MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeader[] to_MaterialDocumentHeaderField;
        
        private string[] customerField;
        
        private string[] storageLocationField;
        
        private string[] wBSElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] MaterialDocument {
            get {
                return this.materialDocumentField;
            }
            set {
                this.materialDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocumentItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] MaterialDocumentItem {
            get {
                return this.materialDocumentItemField;
            }
            set {
                this.materialDocumentItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocumentYear", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] MaterialDocumentYear {
            get {
                return this.materialDocumentYearField;
            }
            set {
                this.materialDocumentYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Material", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Plant", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsMovementIsCancelled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool>[] GoodsMovementIsCancelled {
            get {
                return this.goodsMovementIsCancelledField;
            }
            set {
                this.goodsMovementIsCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Batch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsMovementType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] GoodsMovementType {
            get {
                return this.goodsMovementTypeField;
            }
            set {
                this.goodsMovementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PurchaseOrder {
            get {
                return this.purchaseOrderField;
            }
            set {
                this.purchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrderItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PurchaseOrderItem {
            get {
                return this.purchaseOrderItemField;
            }
            set {
                this.purchaseOrderItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsMovementRefDocType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] GoodsMovementRefDocType {
            get {
                return this.goodsMovementRefDocTypeField;
            }
            set {
                this.goodsMovementRefDocTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsMovementReasonCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] GoodsMovementReasonCode {
            get {
                return this.goodsMovementReasonCodeField;
            }
            set {
                this.goodsMovementReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GLAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] GLAccount {
            get {
                return this.gLAccountField;
            }
            set {
                this.gLAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocumentItemText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] MaterialDocumentItemText {
            get {
                return this.materialDocumentItemTextField;
            }
            set {
                this.materialDocumentItemTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiscalYear", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] FiscalYear {
            get {
                return this.fiscalYearField;
            }
            set {
                this.fiscalYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("to_MaterialDocumentHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeader[] to_MaterialDocumentHeader {
            get {
                return this.to_MaterialDocumentHeaderField;
            }
            set {
                this.to_MaterialDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StorageLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] StorageLocation {
            get {
                return this.storageLocationField;
            }
            set {
                this.storageLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WBSElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] WBSElement {
            get {
                return this.wBSElementField;
            }
            set {
                this.wBSElementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/MaterialDocumentGet/")]
    public partial class MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeader {
        
        private MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeaderA_MaterialDocumentHeaderType a_MaterialDocumentHeaderTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeaderA_MaterialDocumentHeaderType A_MaterialDocumentHeaderType {
            get {
                return this.a_MaterialDocumentHeaderTypeField;
            }
            set {
                this.a_MaterialDocumentHeaderTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/MaterialDocumentGet/")]
    public partial class MaterialDocumentGetResponseA_MaterialDocumentItemTypeTo_MaterialDocumentHeaderA_MaterialDocumentHeaderType {
        
        private string[] materialDocumentField;
        
        private string[] materialDocumentYearField;
        
        private string[] createdByUserField;
        
        private string[] creationTimeField;
        
        private string[] creationDateField;
        
        private string[] documentDateField;
        
        private string[] goodsMovementCodeField;
        
        private string[] inventoryTransactionTypeField;
        
        private string[] materialDocumentHeaderTextField;
        
        private string[] postingDateField;
        
        private string[] referenceDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] MaterialDocument {
            get {
                return this.materialDocumentField;
            }
            set {
                this.materialDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocumentYear", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] MaterialDocumentYear {
            get {
                return this.materialDocumentYearField;
            }
            set {
                this.materialDocumentYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreatedByUser", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreatedByUser {
            get {
                return this.createdByUserField;
            }
            set {
                this.createdByUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreationTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GoodsMovementCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] GoodsMovementCode {
            get {
                return this.goodsMovementCodeField;
            }
            set {
                this.goodsMovementCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InventoryTransactionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] InventoryTransactionType {
            get {
                return this.inventoryTransactionTypeField;
            }
            set {
                this.inventoryTransactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialDocumentHeaderText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] MaterialDocumentHeaderText {
            get {
                return this.materialDocumentHeaderTextField;
            }
            set {
                this.materialDocumentHeaderTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostingDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] ReferenceDocument {
            get {
                return this.referenceDocumentField;
            }
            set {
                this.referenceDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CallMaterialDocumentGetCompletedEventHandler(object sender, CallMaterialDocumentGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallMaterialDocumentGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallMaterialDocumentGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MaterialDocumentGetResponseA_MaterialDocumentItemType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MaterialDocumentGetResponseA_MaterialDocumentItemType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591