//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArxivarSAPIntegration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/outbounddeliveryget")]
        public string ArxivarSAPIntegration_CulliganSapService_OutboundDeliveryGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_CulliganSapService_OutboundDeliveryGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/businesspartnerget")]
        public string ArxivarSAPIntegration_BusinessPartner_BusinessPartnerGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_BusinessPartner_BusinessPartnerGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/salesorderget")]
        public string ArxivarSAPIntegration_SalesOrderGet_SalesOrderGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_SalesOrderGet_SalesOrderGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/materialdocumentget")]
        public string ArxivarSAPIntegration_MaterialDocumentGet_MaterialDocumentGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_MaterialDocumentGet_MaterialDocumentGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/supplierinvoiceget")]
        public string ArxivarSAPIntegration_SupplierInvoiceGet_SupplierInvoiceGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_SupplierInvoiceGet_SupplierInvoiceGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/suppliergetsingle")]
        public string ArxivarSAPIntegration_SupplierGetSingle_SupplierGetSingle {
            get {
                return ((string)(this["ArxivarSAPIntegration_SupplierGetSingle_SupplierGetSingle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://l150056-iflmap.hcisbp.us2.hana.ondemand.com/cxf/invoicesget")]
        public string ArxivarSAPIntegration_InvoicesGet_InvoicesGet {
            get {
                return ((string)(this["ArxivarSAPIntegration_InvoicesGet_InvoicesGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CADRBS-09;Initial Catalog=SAP_BI_old;User ID=culsa09;Password=?Yellow" +
            "tree")]
        public string SAP_BI_oldConnectionString {
            get {
                return ((string)(this["SAP_BI_oldConnectionString"]));
            }
        }
    }
}
