//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ArxivarSAPIntegration.SupplierGetSingle {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SupplierGetSingleSOAP", Namespace="http://www.culligan.it/SupplierGetSingle/")]
    public partial class SupplierGetSingle : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallSupplierGetSingleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SupplierGetSingle() {
            this.Url = global::ArxivarSAPIntegration.Properties.Settings.Default.ArxivarSAPIntegration_SupplierGetSingle_SupplierGetSingle;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallSupplierGetSingleCompletedEventHandler CallSupplierGetSingleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.culligan.it/SupplierGetSingle", RequestElementName="SupplierGetSingle", RequestNamespace="http://www.culligan.it/SupplierGetSingle/", ResponseElementName="SupplierGetSingleResponse", ResponseNamespace="http://www.culligan.it/SupplierGetSingle/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("A_BusinessPartner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("A_BusinessPartnerType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SupplierGetSingleResponseA_BusinessPartnerType[] CallSupplierGetSingle([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LastRunDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cdForni) {
            object[] results = this.Invoke("CallSupplierGetSingle", new object[] {
                        LastRunDate,
                        cdForni});
            return ((SupplierGetSingleResponseA_BusinessPartnerType[])(results[0]));
        }
        
        /// <remarks/>
        public void CallSupplierGetSingleAsync(string LastRunDate, string cdForni) {
            this.CallSupplierGetSingleAsync(LastRunDate, cdForni, null);
        }
        
        /// <remarks/>
        public void CallSupplierGetSingleAsync(string LastRunDate, string cdForni, object userState) {
            if ((this.CallSupplierGetSingleOperationCompleted == null)) {
                this.CallSupplierGetSingleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallSupplierGetSingleOperationCompleted);
            }
            this.InvokeAsync("CallSupplierGetSingle", new object[] {
                        LastRunDate,
                        cdForni}, this.CallSupplierGetSingleOperationCompleted, userState);
        }
        
        private void OnCallSupplierGetSingleOperationCompleted(object arg) {
            if ((this.CallSupplierGetSingleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallSupplierGetSingleCompleted(this, new CallSupplierGetSingleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SupplierGetSingle/")]
    public partial class SupplierGetSingleResponseA_BusinessPartnerType {
        
        private string[] businessPartnerFullNameField;
        
        private string[] businessPartnerNameField;
        
        private string[] creationDateField;
        
        private string[] lastChangeDateField;
        
        private SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerAddressA_BusinessPartnerAddressType[] to_BusinessPartnerAddressField;
        
        private SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerTaxA_BusinessPartnerTaxNumberType[] to_BusinessPartnerTaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessPartnerFullName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] BusinessPartnerFullName {
            get {
                return this.businessPartnerFullNameField;
            }
            set {
                this.businessPartnerFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessPartnerName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] BusinessPartnerName {
            get {
                return this.businessPartnerNameField;
            }
            set {
                this.businessPartnerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LastChangeDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] LastChangeDate {
            get {
                return this.lastChangeDateField;
            }
            set {
                this.lastChangeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_BusinessPartnerAddressType", typeof(SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerAddressA_BusinessPartnerAddressType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerAddressA_BusinessPartnerAddressType[] to_BusinessPartnerAddress {
            get {
                return this.to_BusinessPartnerAddressField;
            }
            set {
                this.to_BusinessPartnerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_BusinessPartnerTaxNumberType", typeof(SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerTaxA_BusinessPartnerTaxNumberType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerTaxA_BusinessPartnerTaxNumberType[] to_BusinessPartnerTax {
            get {
                return this.to_BusinessPartnerTaxField;
            }
            set {
                this.to_BusinessPartnerTaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SupplierGetSingle/")]
    public partial class SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerAddressA_BusinessPartnerAddressType {
        
        private string[] cityCodeField;
        
        private string[] cityNameField;
        
        private string[] countryField;
        
        private string[] districtField;
        
        private string[] fullNameField;
        
        private string[] streetNameField;
        
        private string[] postalCodeField;
        
        private string[] regionField;
        
        private string[][] to_EmailAddressField;
        
        private string[][] to_FaxNumberField;
        
        private string[][] to_MobilePhoneNumberField;
        
        private string[][] to_PhoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CityCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CityName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Country", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("District", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostalCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Region", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_AddressEmailAddressType", typeof(string[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EmailAddress", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] to_EmailAddress {
            get {
                return this.to_EmailAddressField;
            }
            set {
                this.to_EmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_AddressFaxNumberType", typeof(string[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FaxNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] to_FaxNumber {
            get {
                return this.to_FaxNumberField;
            }
            set {
                this.to_FaxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_AddressPhoneNumberType", typeof(string[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PhoneNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] to_MobilePhoneNumber {
            get {
                return this.to_MobilePhoneNumberField;
            }
            set {
                this.to_MobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("A_AddressPhoneNumberType", typeof(string[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PhoneNumber", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] to_PhoneNumber {
            get {
                return this.to_PhoneNumberField;
            }
            set {
                this.to_PhoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.culligan.it/SupplierGetSingle/")]
    public partial class SupplierGetSingleResponseA_BusinessPartnerTypeTo_BusinessPartnerTaxA_BusinessPartnerTaxNumberType {
        
        private string[] bPTaxTypeField;
        
        private string[] bPTaxNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTaxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] BPTaxType {
            get {
                return this.bPTaxTypeField;
            }
            set {
                this.bPTaxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BPTaxNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] BPTaxNumber {
            get {
                return this.bPTaxNumberField;
            }
            set {
                this.bPTaxNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CallSupplierGetSingleCompletedEventHandler(object sender, CallSupplierGetSingleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallSupplierGetSingleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallSupplierGetSingleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SupplierGetSingleResponseA_BusinessPartnerType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SupplierGetSingleResponseA_BusinessPartnerType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591